id: A61B10121
title: The Prayer in Six Vajra Lines
type: translation
pechas:
- I17338BBE
- I7AABA454
- IB3BC31FD
- I1DDE7345
- I4406340A
- I1EEEE631
- IEBD9729D
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - nl
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:32:55.090017
  last_modified_at: 2023-01-04 11:32:55.090023
  collections:
  - Chokgyur Dechen Lingpa
  - Works of Tibetan Masters
alignment_to_base:
  I17338BBE/ECAA: 2D86
  I7AABA454/BCEF: 2D86
  IB3BC31FD/E353: 2D86
  I1DDE7345/E59E: 2D86
  I4406340A/9D9E: 2D86
  I1EEEE631/A348: 2D86
  IEBD9729D/A8B8: 2D86
